services:
  travel-integration-service-rabbitmq:
    image: rabbitmq:3.13.3-management-alpine
    container_name: 'rabbitmq'
    volumes:
      - ./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./config/definitions.json:/etc/rabbitmq/definitions.json
    ports:
      - '5672:5672'
      - '15672:15672'
